### ISSUE TITLE
Password wrong?

### ISSUE THREAD

**Issue by ZeeDoes** [ianklatzco/twitter-to-bsky#27]
Type [I UNDERSTAND]: I UNDERSTAND
Traceback (most recent call last):
  File "C:\Users\Linds\Desktop\twitter-to-bsky-master\main.py", line 70, in <module>
    main()
    ~~~~^^
  File "C:\Users\Linds\Desktop\twitter-to-bsky-master\main.py", line 66, in main
    atpt.login(USERNAME, PASSWORD)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Linds\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\atprototools\__init__.py", line 19, in login
    raise ValueError("No access token, is your password wrong?")
ValueError: No access token, is your password wrong?

The above is what I get, even after changing my password w/o any symbols to make it easier.

The ^ are pointing at the ( and ) at the end of main 
and (USERNAME, PASSWORD)

any help would be grateful

**Comment by webash** [comment]
I suggest using an app password - this should resolve this fault

**Comment by ZeeDoes** [comment]
> I suggest using an app password - this should resolve this fault

Whats an app password?

**Comment by webash** [comment]
https://bsky.app/settings/app-passwords

**Comment by ZeeDoes** [comment]
Sadly, I am still getting the same error with the app password

**Comment by ZeeDoes** [comment]
![Image](https://github.com/user-attachments/assets/934ee984-01a4-4ad8-bedf-e673d1f31768)

**Comment by webash** [comment]
That's not the right place to fill those in. If you take a look at the instructions, you're supposed to set environment variables and then call the script. Those lines are trying to pull the username and password from the "environ"ment.

Since it looks like you're on Windows (the commands given in these instructions are for Bash-esque Linux), and since you're modifying the script anyway: remove the `os.environ.get()` function from around your username and password strings and just set `USERNAME` and `PASSWORD` directly by replacing those 2 lines with this:

```
USERNAME = "zeedoes.bsky.social"
PASSWORD = " password goes here " 
```

**⚠️ However I'd strongly caution you from running arbitrary Python code from random strangers on the Internet without a basic understanding of the code you're running.**

**Comment by ZeeDoes** [comment]
You're beautiful, thank you.

**Comment by webash** [comment]
😅 you're welcome. Mind closing off the issue?
